// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqoD4MKRIq8kU7UR9J-puOdnwyPbxKZAA',
    appId: '1:413970286730:android:60e69930ae782e54f40573',
    messagingSenderId: '413970286730',
    projectId: 'pickmyplastic',
    storageBucket: 'pickmyplastic.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClokZdwyYCqRKgRg6fm-0RpXfVg6yHeP8',
    appId: '1:413970286730:ios:d34ffbc261e95a22f40573',
    messagingSenderId: '413970286730',
    projectId: 'pickmyplastic',
    storageBucket: 'pickmyplastic.appspot.com',
    iosClientId: '413970286730-29996g72j0h2jd8o8drv7di5meg0o9i5.apps.googleusercontent.com',
    iosBundleId: 'com.example.pickMyPlastic',
  );
}
